name: CI Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Step 3: Install build dependencies
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libpq-dev python3-dev

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --verbose
    
    - name: Running app
      run: |
        nohup python app.py

    - name: Wait for Flask app to start
      run: sleep 5  # Wait for 5 seconds for the Flask app to be ready (adjust if necessary)

    # Step 4: Install Newman (for running Postman tests)
    - name: Install Newman
      run: npm install -g newman


    # Step 5: Run API tests using Newman
    - name: Run API tests
      run: newman run tests/postman_collection.json